import type { FormData } from "@/types";
import { emptyCapitalUse } from "./constants";

export const getDefaultValues = (): FormData => ({
  startupName: "",
  vertical: "AI",
  verticalOther: "",
  founders: [{ name: "", email: "", phone: "", linkedin: "" }],
  model: "B2B",
  stage: "Ideia",
  targetCustomer: "",
  painUrgency: "",
  valueProp: "",
  interviewsCount: "",
  validatedHypothesis: "",
  ideaEvidence: "",
  icp: "",
  audience: "",
  psfEvidence: "entrevistas",
  pilotType: "planejado",
  pilotSummary: "",
  acv: "",
  mau: "",
  mrr: "",
  growth3m: "",
  churn: "",
  primaryChannel: "",
  weeklyDedication: "10-20",
  teamComposition: "solo",
  teamSize: undefined as any,
  fullTime: "Sim",
  challenge: "",
  hasRaised: "Nao",
  raisedAmount: "",
  investors: "",
  executionBottleneck: "",
  runwayMonths: "",
  capital: "",
  equity: "",
  capitalUse: { ...emptyCapitalUse },
  capitalPlan: "",
});
